services:
  lander:
    build: .
    image: lander:dev
    container_name: lander-dev
    ports:
      - "3000:3000"
    volumes:
      - ./lander_config:/app/dist/config
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s