# Self-Hosted Services
# Add your services here with their details

services:
  - name: "Portainer"
    description: "Docker container management interface"
    url: "https://google.com"
    icon: "portainer"
    category: "Infrastructure"
    
  - name: "Grafana"
    description: "Analytics and monitoring dashboards"
    url: "http://localhost:3000"
    icon: "grafana"
    category: "Monitoring"
    
  - name: "Nextcloud"
    description: "Personal cloud storage and collaboration"
    url: "http://localhost:8080"
    icon: "nextcloud"
    category: "Storage"
    
  - name: "Home Assistant"
    description: "Smart home automation platform"
    url: "http://localhost:8123"
    icon: "home-assistant"
    category: "Smart Home"
    
  - name: "Plex"
    description: "Media server and streaming platform"
    url: "http://localhost:32400"
    icon: "plex"
    category: "Media"
    
  - name: "Pi-hole"
    description: "Network-wide ad blocking DNS server"
    url: "http://localhost:80"
    icon: "pihole"
    category: "Network"
    
  - name: "Jellyfin"
    description: "Open source media streaming server"
    url: "http://localhost:8096"
    icon: "jellyfin"
    category: "Media"
    
  - name: "Nginx Proxy Manager"
    description: "Reverse proxy with SSL certificate management"
    url: "http://localhost:81"
    icon: "nginx"
    category: "Network"
    
  - name: "Uptime Kuma"
    description: "Self-hosted monitoring and status page"
    url: "http://localhost:3001"
    icon: "uptimekuma"
    category: "Monitoring"
    
  - name: "Vaultwarden"
    description: "Password manager server (Bitwarden compatible)"
    url: "http://localhost:8000"
    icon: "vaultwarden"
    category: "Security"
    
  - name: "PhotoPrism"
    description: "AI-powered photo management and sharing"
    url: "http://localhost:2342"
    icon: "photoprism"
    category: "Media"
    
  - name: "Bookstack"
    description: "Self-hosted documentation and wiki platform"
    url: "http://localhost:6875"
    icon: "bookstack"
    category: "Documentation"
    
  - name: "Sonarr"
    description: "TV series management and automated downloading"
    url: "http://localhost:8989"
    icon: "sonarr"
    category: "Media Management"
    
  - name: "Radarr"
    description: "Movie collection management and automated downloading"
    url: "http://localhost:7878"
    icon: "radarr"
    category: "Media Management"
    
  - name: "Bazarr"
    description: "Subtitle management for Sonarr and Radarr"
    url: "http://localhost:6767"
    icon: "bazarr"
    category: "Media Management"
    
  - name: "Prowlarr"
    description: "Indexer manager for Sonarr, Radarr and Lidarr"
    url: "http://localhost:9696"
    icon: "prowlarr"
    category: "Media Management"
    
  - name: "Transmission"
    description: "Lightweight BitTorrent client"
    url: "http://localhost:9091"
    icon: "transmission"
    category: "Downloads"
    
  - name: "qBittorrent"
    description: "Feature-rich BitTorrent client"
    url: "http://localhost:8081"
    icon: "qbittorrent"
    category: "Downloads"
    
  - name: "Jackett"
    description: "Torrent indexer proxy for Sonarr and Radarr"
    url: "http://localhost:9117"
    icon: "jackett"
    category: "Downloads"
    
  - name: "Ombi"
    description: "Media request platform for Plex and Jellyfin"
    url: "http://localhost:3579"
    icon: "ombi"
    category: "Media Requests"
    
  - name: "Overseerr"
    description: "Request management and media discovery"
    url: "http://localhost:5055"
    icon: "overseerr"
    category: "Media Requests"
    
  - name: "Tautulli"
    description: "Monitoring and statistics for Plex Media Server"
    url: "http://localhost:8182"
    icon: "tautulli"
    category: "Monitoring"
    
  - name: "Heimdall"
    description: "Application dashboard and launcher"
    url: "http://localhost:8080"
    icon: "heimdall"
    category: "Dashboard"
    
  - name: "Homer"
    description: "Static application dashboard"
    url: "http://localhost:8080"
    icon: "homer"
    category: "Dashboard"
    
  - name: "Dashy"
    description: "Customizable application dashboard"
    url: "http://localhost:4000"
    icon: "dashy"
    category: "Dashboard"
    
  - name: "Organizr"
    description: "HTPC/Homelab services organizer"
    url: "http://localhost:80"
    icon: "organizr"
    category: "Dashboard"
    
  - name: "Lidarr"
    description: "Music collection management and automated downloading"
    url: "http://localhost:8686"
    icon: "lidarr"
    category: "Media Management"
    
  - name: "Readarr"
    description: "Book and audiobook collection management"
    url: "http://localhost:8787"
    icon: "readarr"
    category: "Media Management"
    
  - name: "Traefik"
    description: "Modern reverse proxy and load balancer"
    url: "http://localhost:8080"
    icon: "traefik"
    category: "Network"
    
  - name: "Watchtower"
    description: "Automatic Docker container updater"
    url: "http://localhost:8080"
    icon: "watchtower"
    category: "Infrastructure"