name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          ## Changes in ${{ github.ref_name }}
          
          ### Docker Image
          ```bash
          docker run -d --name lander -p 3000:3000 -v ./config:/app/dist/config ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          ```
          
          ### Quick Start with Docker Compose
          ```yaml
          services:
            lander:
              image: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
              container_name: lander
              ports:
                - "3000:3000"
              volumes:
                - ./config:/app/dist/config
              restart: unless-stopped
          ```
          
          See the [README](https://github.com/${{ github.repository }}#readme) for full documentation.
        draft: false
        prerelease: false